version: '3'

services:
  spring-boot-app:
    build:
      context: ./backend # Update this to point to your Spring Boot app directory
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/rms
      - ANOTHER_ENV_VAR=value_here # Add more environment variables if needed
    depends_on:
      - db
      - keycloak

  angular-app:
    build:
      context: ./frontend # Update this to point to your Angular app directory
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - spring-boot-app

  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin # Change to a secure password

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=binnouhab
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rms
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
